[package]
name = "rbitcoin-mempool"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Cluster mempool with InRam buffers + private sidecar files under datadir/mempool/"

[dependencies]
rbitcoin-log = { workspace = true }
rbitcoin-consensus = { workspace = true }
bitcoin = { workspace = true }

[dev-dependencies]
rbitcoin-store = { workspace = true }

[lints]
workspace = true
